### ISSUE TITLE
do full  end-to-end testing and QA  of location based authorization

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/media#69] opened 2016-06-08 21:46 UTC
- [ ] ensure stacks-test and embed-dev have latest master branch deployed, to mimic what will be deployed to production
- [ ] validate access works as expected for stanford only, location-restricted and dark content

@LynnMcRae  could we have:
- an image test object with location based rights?
- a media test object with location based rights?

confirmed that "file" based rights work, but can't confirm media and image without test objects.

https://stacks-test.stanford.edu/file/druid:xv428cw8400/JessieSaysNo-Fast.mov

**Comment by ndushay** [comment] 2016-06-08 22:27
purl-test has latest digital_stacks_rails and sul-embed code in place with location based rights;  the only test object with this is 

http://purl-test.stanford.edu/xv428cw8400  

and it's only the last file with location based rights.

Confirmed that we get a rails "access forbidden" 403  in safari and firefox when attempting to download this file.

**Comment by ndushay** [comment] 2016-06-23 21:56
information about test objects for rights/locations gathered together at https://consul.stanford.edu/display/chimera/Test+objects+for+rights+metadata

**Comment by ndushay** [comment] 2016-07-19 22:50
working on test plan doc:  https://docs.google.com/spreadsheets/d/1U5fAKw2sbGMs6eztfUQQ1GEWAi1HuSkIIB8wJ2zioBI/edit#gid=0

**Comment by ndushay** [comment] 2016-07-20 01:23
@LynnMcRae will fill druids into the test plan doc for test objects we already have.

**Comment by peetucket** [comment] 2016-07-27 21:54
Can be tested using safari since location based auth is server based and does not depend on client

**Comment by LynnMcRae** [comment] 2016-08-24 22:31
While we found a few presentation anomalies and a flash player issue for separate tickets, the location rights interpretation was spot on for files, images, video, audio and download. The test objects page has been broupght up to date. Closing this ticket

**Closed as completed** 2016-08-24 22:31 UTC
Labels: media, prod-blocker
