### ISSUE TITLE
sul-streaming: update rtmp links on collections.stanford.edu

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/media#86] opened 2016-06-24 21:23 UTC
"update the rtmp links on collections.stanford.edu  to point to rtmp on sul-mediaserver (alias for wowza-prod)  instead of to sul-streaming."

These links only exist for bucky and mjf.

The content at collections.stanford.edu, such as the Bucky audio and video, currently points to the old sul-streaming.stanford.edu server that we want to decommission. We have started migrating content to the new server (see #76), but collections.stanford.edu is more complicated because it is a Java-based web application rather than plain HTML/CSS/JavaScript.

There are probably two ways to perform this part of the migration:
- Change the source code of the application that runs on collections.stanford.edu and restart/redeploy it. Given that this application doesn't seem to have been maintained for years and we don't see a standard way to update and redeploy it, we do NOT prefer this solution.
- Use aliasing/redirecting to direct all requests to the old Wowza server to the new one (preferred solution).

**Comment by ndushay** [comment] 2016-06-28 21:47
currently a won't fix due to plans to be articulated in consul page, blah blah.

**Comment by ndushay** [comment] 2016-06-29 02:00
See https://consul.stanford.edu/display/GAL/sul-streaming+migration and SAR-3189, SAR-3157

**Comment by ndushay** [comment] 2016-06-29 21:30
Change in plans!   We can do this!   We only need to do it for mjf and bucky.

**Comment by ndushay** [comment] 2016-06-29 23:26
This is done for mjf and bucky;   the links on this page are broken:

http://collections.stanford.edu/bucky/bin/page?forward=exploringbucky/moreideas

they are keying off fileIDs like this:  `<a href="/bucky/bin/mediaplayer?fileID=1417336165&n=1">audio1</a>`

I can't figure out where that fileID is defined and/or looked up.   There is no file like that in the bucky media data on sul-streaming or html dirs on the file system on collections-prod.

I'm not confident they were working before.

@hannahfrost - do we need  a process for vetting this work?

**Comment by hannahfrost** [comment] 2016-06-30 00:07
Hmm. those IDs are not meaningful to me either, which means it was designed within the app.... I could dig up what those actual files are, but don't know if we can do anything with that. could we?

**Comment by ndushay** [comment] 2016-06-30 00:08
If we know what the files are, we can make the links actually work, I think.  I can't figure out how it might have worked before.  The collections-prod  box has a fairly confusing set of inter-related web sites.

**Comment by hannahfrost** [comment] 2016-06-30 00:12
ok, I'll see if we can get those files identified on wowza-prod

**Comment by hannahfrost** [comment] 2016-06-30 04:15
I found the file names for all but the second-from-the-bottom (metadata error in the original finding aid that has persisted for a long time). And the bottom link on that page is not broken (it leads to a search result, not media). Hopefully this helps.
[buckyfixes.xlsx](https://github.com/sul-dlss/media/files/340692/buckyfixes.xlsx)

**Comment by ndushay** [comment] 2016-07-01 18:01
So it turns out links like the ones on this page:
http://collections.stanford.edu/bucky/bin/search/advanced/process?clauseMapped%28title%29=architect*&clauseMapped%28dateISO%29=&clauseMapped%28format1%29=audio+OR+audio1+OR+audio2+OR+video+OR+video1+OR+video2&sort=dateStart

work:

http://collections.stanford.edu/bucky/bin/mediaplayer?fileID=157138371X&n=1

so now I'm totally puzzled.   And more convinced those other links were already not working.

I can't figure out if the fileIDs are in a sql database or a solr index somewhere ... and I can't figure out how to get into either if present.

**Comment by ndushay** [comment] 2016-07-01 18:30
I think at this point we can call this done, except there should be some vetting by someone other than me!

**Closed as completed** 2016-07-06 21:58 UTC
Labels: media
